---
# tasks file for backup-local

- name: ensure backup folder exists
  file:
    path: "{{ backup_local_destination }}"
    state: directory
    mode: 0700

- name: copy backup script
  copy:
    src: backup.py
    dest: "{{ backup_local_destination }}/backup_{{ backup_local_name }}.py"
    mode: 0700

- name: configure backup cron job
  cron:
    name: "backup {{ backup_local_name }}"
    minute: "{{ backup_local_minute }}"
    hour: "{{ backup_local_hour }}"
    day: "{{ backup_local_day }}"
    month: "{{ backup_local_month }}"
    weekday:  "{{ backup_local_weekday }}"
    job: "python '{{ backup_local_destination }}/backup_{{ backup_local_name }}.py' '{{ backup_local_name }}' '{{ backup_local_target }}' '{{ backup_local_destination }}' '{{ backup_local_retention_number }}'  >> '{{ backup_local_destination }}/cron_{{ backup_local_name }}.log' 2>&1"
  when: not encrypt_gpg_and_transfer_scp_what_if

- name: configure backup cron job (what-if)
  cron:
    name: "backup {{ backup_local_name }}"
    minute: "{{ backup_local_minute }}"
    hour: "{{ backup_local_hour }}"
    day: "{{ backup_local_day }}"
    month: "{{ backup_local_month }}"
    weekday:  "{{ backup_local_weekday }}"
    job: "python '{{ backup_local_destination }}/backup_{{ backup_local_name }}.py' '{{ backup_local_name }}' '{{ backup_local_target }}' '{{ backup_local_destination }}' '{{ backup_local_retention_number }}' --what-if  >> '{{ backup_local_destination }}/cron_{{ backup_local_name }}.log' 2>&1"
  when: encrypt_gpg_and_transfer_scp_what_if

